package com.example.service

import android.content.Context
import android.util.Log
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import com.example.util.LanguageManager
import com.example.data.local.KundaliEntity
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.FirebaseAuthMultiFactorException
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.auth.MultiFactorResolver
import com.google.firebase.auth.TotpMultiFactorGenerator
import com.google.firebase.firestore.FieldValue
import com.google.firebase.firestore.FirebaseFirestore
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.tasks.await

/**
 * The account has an authenticator (only admins enrol one), so the sign-in is
 * half done: [FirebaseAuthService.finishSignInWithCode] completes it.
 */
class CodeRequired(val resolver: MultiFactorResolver) : Exception("Authenticator code required")

class FirebaseAuthService {

    private companion object {
        /** Firestore refuses a batch larger than this. */
        const val FIRESTORE_BATCH_LIMIT = 450
    }

    private val auth: FirebaseAuth by lazy { FirebaseAuth.getInstance() }
    private val firestore: FirebaseFirestore by lazy { FirebaseFirestore.getInstance() }

    val currentUser: FirebaseUser?
        get() = try {
            auth.currentUser
        } catch (e: Exception) {
            null
        }

    suspend fun signInWithGoogle(context: Context, webClientId: String = ""): Result<FirebaseUser> {
        return try {
            val credentialManager = CredentialManager.create(context)

            // `default_web_client_id` is generated by the Google Services
            // plugin from whichever google-services.json the variant carries, so
            // debug gets the debug project's client and release gets the live
            // one, with no second copy to keep in step. That matters now that
            // the debug build is a separate app on a separate Firebase project:
            // a release client id used against the debug project fails as
            // "No Google account found on this device", which says nothing about
            // the real cause — this app has shipped that message once already
            // for a certificate mismatch.
            //
            // BuildConfig stays as the fallback for a build that has no
            // google-services.json at all; the secrets plugin fills it from
            // .env.
            val generated = runCatching {
                context.getString(app.revati.jyotish.R.string.default_web_client_id)
            }.getOrNull().orEmpty()
            val defaultClientId =
                if (generated.isNotEmpty()) generated
                else app.revati.jyotish.BuildConfig.GOOGLE_WEB_CLIENT_ID
            val clientId = if (webClientId.isNotEmpty()) webClientId else defaultClientId

            if (clientId.isEmpty()) {
                return Result.failure(Exception("Google Web Client ID is not configured. Please add GOOGLE_WEB_CLIENT_ID to .env or strings.xml"))
            }

            val googleIdOption = GetGoogleIdOption.Builder()
                .setFilterByAuthorizedAccounts(false)
                .setServerClientId(clientId)
                .setAutoSelectEnabled(false)
                .build()

            val request = GetCredentialRequest.Builder()
                .addCredentialOption(googleIdOption)
                .build()

            val result = credentialManager.getCredential(context, request)
            val credential = result.credential

            if (credential is CustomCredential && credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
                val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
                val idToken = googleIdTokenCredential.idToken

                val authCredential = GoogleAuthProvider.getCredential(idToken, null)
                val authResult = auth.signInWithCredential(authCredential).await()
                val user = authResult.user
                if (user != null) {
                    Result.success(user)
                } else {
                    Result.failure(Exception("Firebase user is null after sign in"))
                }
            } else {
                Result.failure(Exception("Unsupported credential type"))
            }
        } catch (e: androidx.credentials.exceptions.NoCredentialException) {
            // No Google account is set up on this device, or the user has none that
            // matches. This is not an error to log as a failure — it needs a
            // different message than "sign-in failed", which is what it used to get.
            Log.i("FirebaseAuthService", "No Google credential available on this device")
            Result.failure(
                Exception(
                    LanguageManager.getString(
                        "इस डिवाइस पर कोई Google खाता नहीं मिला। कृपया Settings में Google खाता जोड़ें और दोबारा प्रयास करें।",
                        "No Google account found on this device. Add one in Settings and try again."
                    )
                )
            )
        } catch (e: androidx.credentials.exceptions.GetCredentialCancellationException) {
            Log.i("FirebaseAuthService", "Sign-in cancelled by user")
            Result.failure(Exception(LanguageManager.getString("साइन-इन रद्द किया गया।", "Sign-in cancelled.")))
        } catch (e: FirebaseAuthMultiFactorException) {
            Result.failure(CodeRequired(e.resolver))
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            Log.e("FirebaseAuthService", "Google Sign-In failed", e)
            // Was Result.failure(e), which put the raw Google/Firebase exception
            // text on screen. Callers interpolate this message, so it has to be
            // something a user can read, in their language.
            Result.failure(Exception(readableAuthError(e)))
        }
    }

    /**
     * Email sign-up. Google is not an option for everyone — a phone without a
     * Google account, or a user who simply does not want to link one, still has
     * to get past the sign-in gate.
     */
    suspend fun signUpWithEmail(email: String, password: String, name: String): Result<FirebaseUser> = try {
        val result = auth.createUserWithEmailAndPassword(email.trim(), password).await()
        val user = result.user
        if (user == null) {
            Result.failure(Exception(LanguageManager.getString(
                "खाता नहीं बन सका। कृपया पुनः प्रयास करें।",
                "Could not create the account. Please try again."
            )))
        } else {
            if (name.isNotBlank()) {
                runCatching {
                    user.updateProfile(
                        com.google.firebase.auth.UserProfileChangeRequest.Builder()
                            .setDisplayName(name.trim())
                            .build()
                    ).await()
                }
            }
            // Anyone could previously sign up with an address they did not own,
            // and that address would then start receiving password-reset mail for
            // an account its owner never created. Best-effort: a mail server
            // hiccup must not cost the user the account they just made.
            runCatching { user.sendEmailVerification().await() }
            Result.success(user)
        }
    } catch (e: CancellationException) {
        throw e
    } catch (e: Exception) {
        Log.e("FirebaseAuthService", "Email sign-up failed", e)
        Result.failure(Exception(readableAuthError(e)))
    }

    /** Email sign-in for an account created with [signUpWithEmail]. */
    suspend fun signInWithEmail(email: String, password: String): Result<FirebaseUser> = try {
        val result = auth.signInWithEmailAndPassword(email.trim(), password).await()
        val user = result.user
        if (user == null) {
            Result.failure(Exception(LanguageManager.getString(
                "साइन-इन नहीं हो सका। कृपया पुनः प्रयास करें।",
                "Could not sign in. Please try again."
            )))
        } else {
            Result.success(user)
        }
    } catch (e: FirebaseAuthMultiFactorException) {
        Result.failure(CodeRequired(e.resolver))
    } catch (e: CancellationException) {
        throw e
    } catch (e: Exception) {
        Log.e("FirebaseAuthService", "Email sign-in failed", e)
        Result.failure(Exception(readableAuthError(e)))
    }

    /** The second half of a sign-in that answered [CodeRequired]. Admin-only, so English only. */
    suspend fun finishSignInWithCode(resolver: MultiFactorResolver, code: String): Result<FirebaseUser> = try {
        val hint = resolver.hints.first { it.factorId == TotpMultiFactorGenerator.FACTOR_ID }
        val result = resolver.resolveSignIn(
            TotpMultiFactorGenerator.getAssertionForSignIn(hint.uid, code.trim())
        ).await()
        Result.success(requireNotNull(result.user))
    } catch (e: CancellationException) {
        throw e
    } catch (e: com.google.firebase.auth.FirebaseAuthInvalidCredentialsException) {
        Result.failure(Exception("That code is not right. Use the one your authenticator app shows now."))
    } catch (e: Exception) {
        Log.e("FirebaseAuthService", "Authenticator sign-in failed", e)
        Result.failure(Exception(readableAuthError(e)))
    }

    /**
     * The account's row in `directory/`, which is how the admin panel lists
     * users — Firebase gives a phone no way to list accounts. The rules pin the
     * email to the sign-in's own and the time to the server's.
     */
    suspend fun touchDirectory() {
        val user = currentUser ?: return
        firestore.collection("directory").document(user.uid).set(
            mapOf(
                "email" to user.email,
                "name" to user.displayName.orEmpty().take(100),
                "createdAt" to (user.metadata?.creationTimestamp ?: 0L),
                "lastSeenAt" to FieldValue.serverTimestamp()
            )
        ).await()
    }

    /** Whether an admin has banned this account. The rules already refuse its backups; this is so the app can say so. */
    suspend fun isBanned(): Boolean {
        val user = currentUser ?: return false
        return firestore.collection("bans").document(user.uid).get().await().getBoolean("banned") == true
    }

    /** Sends a password-reset mail; the address may or may not have an account. */
    suspend fun sendPasswordReset(email: String): Result<Unit> = try {
        auth.sendPasswordResetEmail(email.trim()).await()
        Result.success(Unit)
    } catch (e: CancellationException) {
        throw e
    } catch (e: Exception) {
        Log.e("FirebaseAuthService", "Password reset failed", e)
        Result.failure(Exception(readableAuthError(e)))
    }

    /**
     * Firebase's own messages are English-only and written for developers
     * ("The password is invalid or the user does not have a password"). These
     * say what went wrong and what to do about it, in the reader's language.
     */
    private fun readableAuthError(e: Exception): String = when (e) {
        is com.google.firebase.auth.FirebaseAuthWeakPasswordException -> LanguageManager.getString(
            "पासवर्ड कम से कम 6 अक्षर का होना चाहिए।",
            "Use at least 6 characters for the password."
        )
        is com.google.firebase.auth.FirebaseAuthInvalidCredentialsException -> LanguageManager.getString(
            "ईमेल या पासवर्ड सही नहीं है।",
            "That email or password is not right."
        )
        is com.google.firebase.auth.FirebaseAuthUserCollisionException -> LanguageManager.getString(
            "इस ईमेल से खाता पहले से मौजूद है। साइन-इन करें।",
            "An account already exists for this email. Sign in instead."
        )
        is com.google.firebase.auth.FirebaseAuthInvalidUserException -> LanguageManager.getString(
            "इस ईमेल से कोई खाता नहीं मिला। पहले साइन-अप करें।",
            "No account found for this email. Sign up first."
        )
        is com.google.firebase.FirebaseNetworkException -> LanguageManager.getString(
            "इंटरनेट कनेक्शन नहीं है। जुड़ने के बाद पुनः प्रयास करें।",
            "No internet connection. Try again once you are back online."
        )
        // This used to fall through to e.message, which put Firebase's own
        // developer-facing English ("The password is invalid or the user does not
        // have a password") in front of a Hindi-speaking user, and leaked internal
        // detail besides. The raw exception is logged at every call site instead.
        else -> LanguageManager.getString(
            "कुछ गड़बड़ हो गई। कृपया पुनः प्रयास करें।",
            "Something went wrong. Please try again."
        )
    }

    fun signOut() {
        try {
            auth.signOut()
        } catch (e: Exception) {
            Log.e("FirebaseAuthService", "Sign out error", e)
        }
    }

    /**
     * Writes every profile to the signed-in user's own subtree.
     *
     * Documents are keyed on [KundaliEntity.uuid], never on the Room id. The id
     * is autoGenerate, so it starts at 1 on every device; keying on it meant a
     * second phone's first profile silently overwrote the first phone's, and the
     * original was unrecoverable.
     *
     * Firestore caps a batch at 500 writes, so this chunks. It used to send them
     * all in one batch, which threw for anyone with more than 500 saved profiles
     * and took the whole backup down with it.
     */
    suspend fun backupProfilesToCloud(profiles: List<KundaliEntity>): Result<Int> {
        val user = currentUser ?: return Result.failure(Exception("User not authenticated with Firebase"))
        return try {
            val userProfilesRef = firestore.collection("users")
                .document(user.uid)
                .collection("kundali_profiles")

            profiles.chunked(FIRESTORE_BATCH_LIMIT).forEach { chunk ->
                val batch = firestore.batch()
                chunk.forEach { profile ->
                    val docRef = userProfilesRef.document(profile.uuid)
                    val data = mapOf(
                        "uuid" to profile.uuid,
                        "name" to profile.name,
                        "gender" to profile.gender,
                        "dateOfBirth" to profile.dateOfBirth,
                        "timeOfBirth" to profile.timeOfBirth,
                        "placeOfBirth" to profile.placeOfBirth,
                        "latitude" to profile.latitude,
                        "longitude" to profile.longitude,
                        "notes" to profile.notes,
                        "createdAt" to profile.createdAt
                    )
                    batch.set(docRef, data)
                }
                batch.commit().await()
            }
            Result.success(profiles.size)
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            Log.e("FirebaseAuthService", "Failed to backup profiles to cloud", e)
            Result.failure(e)
        }
    }

    suspend fun restoreProfilesFromCloud(): Result<List<KundaliEntity>> {
        val user = currentUser ?: return Result.failure(Exception("User not authenticated with Firebase"))
        return try {
            val snapshot = firestore.collection("users")
                .document(user.uid)
                .collection("kundali_profiles")
                .get()
                .await()

            val profiles = snapshot.documents.mapNotNull { doc ->
                val name = doc.getString("name") ?: return@mapNotNull null
                KundaliEntity(
                    // id stays 0 so Room assigns a fresh local one; identity
                    // travels in uuid. Documents written before schema 6 have no
                    // uuid field, and the document id is the old numeric id — so
                    // fall back to the document id, which is stable per account
                    // even if it collided across devices.
                    id = 0L,
                    uuid = doc.getString("uuid") ?: doc.id,
                    name = name,
                    gender = doc.getString("gender") ?: "MALE",
                    dateOfBirth = doc.getString("dateOfBirth") ?: "",
                    timeOfBirth = doc.getString("timeOfBirth") ?: "",
                    placeOfBirth = doc.getString("placeOfBirth") ?: "",
                    latitude = doc.getDouble("latitude") ?: 28.6139,
                    longitude = doc.getDouble("longitude") ?: 77.2090,
                    notes = doc.getString("notes") ?: "",
                    createdAt = doc.getLong("createdAt") ?: System.currentTimeMillis()
                )
            }
            Result.success(profiles)
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            Log.e("FirebaseAuthService", "Failed to restore profiles from cloud", e)
            Result.failure(e)
        }
    }

    /**
     * Deletes the cloud copy and the account, in that order — but only after the
     * session has been proven fresh.
     *
     * The order used to be: wipe Firestore, then call user.delete(). If the user
     * had signed in more than a few minutes earlier — the ordinary case — delete()
     * threw FirebaseAuthRecentLoginRequiredException, the caller reported "delete
     * failed", and the cloud backup was already gone. Forcing a token refresh
     * first turns that into a clean, recoverable refusal that destroys nothing.
     */
    suspend fun deleteUserDataAndAccount(): Result<Unit> {
        val user = currentUser ?: return Result.failure(Exception("User not authenticated with Firebase"))
        return try {
            // 1. Prove the session is still fresh BEFORE destroying anything.
            //    A stale session fails here, with all the data intact.
            user.getIdToken(true).await()

            // 2. Delete all Firestore cloud backup data for this user, chunked
            //    to stay under Firestore's 500-writes-per-batch limit.
            val userProfilesRef = firestore.collection("users")
                .document(user.uid)
                .collection("kundali_profiles")
                .get()
                .await()

            userProfilesRef.documents.chunked(FIRESTORE_BATCH_LIMIT).forEach { chunk ->
                val batch = firestore.batch()
                chunk.forEach { doc -> batch.delete(doc.reference) }
                batch.commit().await()
            }
            firestore.collection("users").document(user.uid).delete().await()
            firestore.collection("directory").document(user.uid).delete().await()

            // 3. Delete the Firebase Auth user account
            user.delete().await()
            Result.success(Unit)
        } catch (e: com.google.firebase.auth.FirebaseAuthRecentLoginRequiredException) {
            Log.e("FirebaseAuthService", "Re-authentication required before deleting account", e)
            Result.failure(Exception(LanguageManager.getString(
                "सुरक्षा के लिए, खाता हटाने से पहले कृपया पुनः साइन-इन करें।",
                "For security, please sign in again before deleting your account."
            )))
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            Log.e("FirebaseAuthService", "Failed to delete user data and account", e)
            Result.failure(e)
        }
    }
}
